// electron-react/src/components/workspace/DockviewHost.tsx
import { useCallback, useEffect, useRef } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import {
  DockviewComponent,
  type DockviewApi,
  type GroupPanelPartInitParameters,
  type IContentRenderer,
} from 'dockview-core'

import { BackendStatusPane } from '../backend/BackendStatusPane'
import { ConversationPane } from '../conversation/ConversationPane'

const backendStatusPanelId = 'backend-status'
const conversationPanelId = 'conversation'
const floatingPanelMargin = 24
const lockedGroupMode = 'no-drop-target'

/** Represents the props used to register workspace panel openers with the shell. */
interface DockviewHostProps {
  registerOpenConversationPanel?: (opener: (() => void) | null) => void
  registerOpenBackendStatusPanel?: (opener: (() => void) | null) => void
}

/** Represents one React render callback used inside a Dockview content renderer. */
type PanelRenderFactory = () => JSX.Element

/** Renders one React component into a Dockview panel body. */
class ReactContentRenderer implements IContentRenderer {
  readonly element = document.createElement('div')
  private readonly renderPanel: PanelRenderFactory
  private root: Root | null = null

  /** Stores the React panel render function and prepares the host element. */
  constructor(renderPanel: PanelRenderFactory) {
    this.renderPanel = renderPanel
    this.element.style.height = '100%'
    this.element.style.minHeight = '0'
    this.element.style.width = '100%'
  }

  /** Mounts the React panel into the Dockview content element. */
  init(_parameters: GroupPanelPartInitParameters): void {
    this.root = createRoot(this.element)
    this.root.render(this.renderPanel())
  }

  /** Unmounts the React panel when Dockview disposes the content renderer. */
  dispose(): void {
    this.root?.unmount()
    this.root = null
  }
}

/** Creates one Dockview renderer for the requested panel component name. */
function createComponentRenderer(componentName: string): IContentRenderer {
  if (componentName === 'backend-status') {
    return new ReactContentRenderer(() => <BackendStatusPane />)
  }

  if (componentName === 'conversation') {
    return new ReactContentRenderer(() => <ConversationPane />)
  }

  throw new Error(`Unsupported Dockview component: ${componentName}`)
}

/** Returns the current Dockview host bounds used to size floating panels. */
function getHostBounds(hostElement: HTMLDivElement | null): { width: number; height: number } {
  const width = hostElement?.clientWidth ?? window.innerWidth
  const height = hostElement?.clientHeight ?? window.innerHeight

  return { width, height }
}

/** Returns the initial floating bounds for the main chat panel. */
function getConversationFloatingBounds(
  hostElement: HTMLDivElement | null,
): { width: number; height: number; x: number; y: number } {
  const { width: hostWidth, height: hostHeight } = getHostBounds(hostElement)
  const width = Math.min(Math.max(Math.round(hostWidth * 0.72), 720), hostWidth - floatingPanelMargin * 2)
  const height = Math.min(Math.max(Math.round(hostHeight * 0.8), 560), hostHeight - floatingPanelMargin * 2)
  const x = Math.max(floatingPanelMargin, Math.round((hostWidth - width) / 2))
  const y = Math.max(floatingPanelMargin, Math.round((hostHeight - height) / 2))

  return { width, height, x, y }
}

/** Returns the initial floating bounds for the backend status panel. */
function getBackendStatusFloatingBounds(
  hostElement: HTMLDivElement | null,
): { width: number; height: number; x: number; y: number } {
  const { width: hostWidth, height: hostHeight } = getHostBounds(hostElement)
  const maxWidth = Math.max(280, hostWidth - floatingPanelMargin * 2)
  const maxHeight = Math.max(240, hostHeight - floatingPanelMargin * 2)
  const width = Math.min(Math.max(Math.round(hostWidth * 0.34), 400), Math.min(560, maxWidth))
  const height = Math.min(Math.max(Math.round(hostHeight * 0.5), 320), Math.min(460, maxHeight))
  const x = Math.max(floatingPanelMargin, hostWidth - width - floatingPanelMargin)
  const y = floatingPanelMargin

  return { width, height, x, y }
}

/** Locks one Dockview group so it cannot accept additional dropped panels. */
function lockPanelGroup(dockviewApi: DockviewApi | null, panelId: string): void {
  const panel = dockviewApi?.getPanel(panelId)

  if (!panel) {
    return
  }

  panel.api.group.locked = lockedGroupMode
}

/** Renders and manages the Dockview workspace host for the React migration shell. */
export function DockviewHost({
  registerOpenConversationPanel = () => {},
  registerOpenBackendStatusPanel = () => {},
}: DockviewHostProps): JSX.Element {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const dockviewApiRef = useRef<DockviewApi | null>(null)

  /** Focuses the existing chat panel or creates it when it is missing. */
  const ensureConversationPanelOpen = useCallback((): void => {
    const dockviewApi = dockviewApiRef.current

    if (!dockviewApi) {
      return
    }

    const existingPanel = dockviewApi.getPanel(conversationPanelId)

    if (existingPanel) {
      lockPanelGroup(dockviewApi, conversationPanelId)
      existingPanel.api.setActive()
      dockviewApi.focus()
      return
    }

    const panel = dockviewApi.addPanel({
      id: conversationPanelId,
      component: 'conversation',
      title: 'Chat',
      floating: getConversationFloatingBounds(hostRef.current),
    })

    panel.api.group.locked = lockedGroupMode
  }, [])

  /** Focuses the existing backend status panel or creates it when it is missing. */
  const ensureBackendStatusPanelOpen = useCallback((): void => {
    const dockviewApi = dockviewApiRef.current

    if (!dockviewApi) {
      return
    }

    const existingPanel = dockviewApi.getPanel(backendStatusPanelId)

    if (existingPanel) {
      lockPanelGroup(dockviewApi, backendStatusPanelId)
      existingPanel.api.setActive()
      dockviewApi.focus()
      return
    }

    const panel = dockviewApi.addPanel({
      id: backendStatusPanelId,
      component: 'backend-status',
      title: 'Backend Status',
      floating: getBackendStatusFloatingBounds(hostRef.current),
    })

    panel.api.group.locked = lockedGroupMode
  }, [])

  useEffect(() => {
    if (!hostRef.current) {
      return
    }

    const dockview = new DockviewComponent(hostRef.current, {
      createComponent: (options) => createComponentRenderer(options.name),
      floatingGroupBounds: 'boundedWithinViewport',
    })

    dockviewApiRef.current = dockview.api
    const addPanelDisposable = dockview.api.onDidAddPanel((panel) => {
      panel.api.group.locked = lockedGroupMode
    })

    registerOpenConversationPanel(ensureConversationPanelOpen)
    registerOpenBackendStatusPanel(ensureBackendStatusPanelOpen)
    ensureConversationPanelOpen()

    return () => {
      addPanelDisposable.dispose()
      registerOpenConversationPanel(null)
      registerOpenBackendStatusPanel(null)
      dockviewApiRef.current = null
      dockview.dispose()
    }
  }, [
    ensureBackendStatusPanelOpen,
    ensureConversationPanelOpen,
    registerOpenBackendStatusPanel,
    registerOpenConversationPanel,
  ])

  return (
    <div
      ref={hostRef}
      className="vide-dockview dockview-theme-dark h-full min-h-0 w-full"
    />
  )
}

// electron/src/lib/components/workspace/DockviewHost.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { mount, unmount } from 'svelte'
  import {
    DockviewComponent,
    type DockviewApi,
    type GroupPanelPartInitParameters,
    type IContentRenderer,
  } from 'dockview-core'
  import BackendStatusPane from '../backend/BackendStatusPane.svelte'
  import ConversationPane from '../conversation/ConversationPane.svelte'
  import { theme } from '../../theme/theme-state.svelte'

  const backendStatusPanelId = 'backend-status'
  const conversationPanelId = 'conversation'

  let {
    registerOpenConversationPanel = () => {},
    registerOpenBackendStatusPanel = () => {},
  }: {
    registerOpenConversationPanel?: (opener: (() => void) | null) => void
    registerOpenBackendStatusPanel?: (opener: (() => void) | null) => void
  } = $props()

  let hostElement: HTMLDivElement | null = null
  let dockviewApi = $state<DockviewApi | null>(null)
  let dockviewThemeClass = $derived(theme.current === 'light' ? 'dockview-theme-light' : 'dockview-theme-dark')

  /** Renders the chat panel content inside one Dockview panel body. */
  class ConversationContentRenderer implements IContentRenderer {
    readonly element = document.createElement('div')

    #component: Record<string, any> | null = null

    constructor() {
      this.element.style.height = '100%'
      this.element.style.minHeight = '0'
      this.element.style.width = '100%'
    }

    init(_parameters: GroupPanelPartInitParameters): void {
      this.#component = mount(ConversationPane, {
        target: this.element,
      })
    }

    dispose(): void {
      if (!this.#component) {
        return
      }

      void unmount(this.#component)
      this.#component = null
    }
  }

  /** Renders the backend status panel content inside one Dockview panel body. */
  class BackendStatusContentRenderer implements IContentRenderer {
    readonly element = document.createElement('div')

    #component: Record<string, any> | null = null

    constructor() {
      this.element.style.height = '100%'
      this.element.style.minHeight = '0'
      this.element.style.width = '100%'
    }

    init(_parameters: GroupPanelPartInitParameters): void {
      this.#component = mount(BackendStatusPane, {
        target: this.element,
      })
    }

    dispose(): void {
      if (!this.#component) {
        return
      }

      void unmount(this.#component)
      this.#component = null
    }
  }

  /** Creates one Dockview renderer for the requested panel component name. */
  function createComponentRenderer(componentName: string): IContentRenderer {
    if (componentName === 'backend-status') {
      return new BackendStatusContentRenderer()
    }

    if (componentName === 'conversation') {
      return new ConversationContentRenderer()
    }

    throw new Error(`Unsupported Dockview component: ${componentName}`)
  }

  /** Focuses the existing chat panel or creates it when it is missing. */
  function ensureConversationPanelOpen(): void {
    if (!dockviewApi) {
      return
    }

    const existingPanel = dockviewApi.getPanel(conversationPanelId)

    if (existingPanel) {
      existingPanel.api.setActive()
      dockviewApi.focus()
      return
    }

    dockviewApi.addPanel({
      id: conversationPanelId,
      component: 'conversation',
      title: 'Chat',
    })
  }

  /** Focuses the existing backend status panel or creates it when it is missing. */
  function ensureBackendStatusPanelOpen(): void {
    if (!dockviewApi) {
      return
    }

    const existingPanel = dockviewApi.getPanel(backendStatusPanelId)

    if (existingPanel) {
      existingPanel.api.setActive()
      dockviewApi.focus()
      return
    }

    const referenceConversationPanel = dockviewApi.getPanel(conversationPanelId)

    dockviewApi.addPanel({
      id: backendStatusPanelId,
      component: 'backend-status',
      title: 'Backend Status',
      ...(referenceConversationPanel
        ? {
            position: {
              direction: 'right' as const,
              referencePanel: conversationPanelId,
            },
          }
        : {}),
    })
  }

  $effect(() => {
    if (!hostElement) {
      return
    }

    const dockview = new DockviewComponent(hostElement, {
      createComponent: (options) => createComponentRenderer(options.name),
    })

    dockviewApi = dockview.api
    registerOpenConversationPanel(ensureConversationPanelOpen)
    registerOpenBackendStatusPanel(ensureBackendStatusPanelOpen)
    ensureConversationPanelOpen()

    return () => {
      registerOpenConversationPanel(null)
      registerOpenBackendStatusPanel(null)
      dockviewApi = null
      dockview.dispose()
    }
  })
</script>

<div
  bind:this={hostElement}
  class={`vide-dockview ${dockviewThemeClass} h-full min-h-0 w-full`}
></div>
