// electron/src/lib/components/backend/BackendStatusPane.svelte
<svelte:options runes={true} />

<script lang="ts">
  import {
    backendStatusState,
    type BackendHealthStatus,
  } from '../../session/backend-status-state.svelte'
  import { getDefaultSessionServerUrl } from '../../session/session-client'
  import { sessionState } from '../../session/session-state.svelte'
  import type { SessionConnectionStatus } from '../../types/session'

  const backendStatus = backendStatusState
  const session = sessionState
  const sessionEndpoint = getDefaultSessionServerUrl()

  let backendHealthLabel = $derived(getBackendHealthLabel(backendStatus.healthStatus))
  let backendHealthTone = $derived(getBackendHealthTone(backendStatus.healthStatus))
  let sessionConnectionLabel = $derived(getSessionConnectionLabel(session.connectionStatus))
  let sessionConnectionTone = $derived(getSessionConnectionTone(session.connectionStatus))
  let lastCheckedLabel = $derived(formatLastCheckedAt(backendStatus.lastCheckedAt))

  /** Returns the human-readable label for one backend health state. */
  function getBackendHealthLabel(status: BackendHealthStatus): string {
    if (status === 'healthy') {
      return 'Healthy'
    }

    if (status === 'unreachable') {
      return 'Unreachable'
    }

    if (status === 'checking') {
      return 'Checking'
    }

    return 'Idle'
  }

  /** Returns the badge classes for one backend health state. */
  function getBackendHealthTone(status: BackendHealthStatus): string {
    if (status === 'healthy') {
      return 'border-emerald-500/30 bg-emerald-500/12 text-emerald-300'
    }

    if (status === 'unreachable') {
      return 'border-rose-500/30 bg-rose-500/12 text-rose-300'
    }

    if (status === 'checking') {
      return 'border-sky-500/30 bg-sky-500/12 text-sky-300'
    }

    return 'border-[var(--color-border)] bg-[var(--color-panel)] text-[var(--color-muted)]'
  }

  /** Returns the human-readable label for one session connection state. */
  function getSessionConnectionLabel(status: SessionConnectionStatus): string {
    if (status === 'connected') {
      return 'Connected'
    }

    if (status === 'connecting') {
      return 'Connecting'
    }

    return 'Disconnected'
  }

  /** Returns the badge classes for one session connection state. */
  function getSessionConnectionTone(status: SessionConnectionStatus): string {
    if (status === 'connected') {
      return 'border-emerald-500/30 bg-emerald-500/12 text-emerald-300'
    }

    if (status === 'connecting') {
      return 'border-sky-500/30 bg-sky-500/12 text-sky-300'
    }

    return 'border-rose-500/30 bg-rose-500/12 text-rose-300'
  }

  /** Formats one health-check timestamp for display in the panel. */
  function formatLastCheckedAt(timestamp: number | null): string {
    if (timestamp === null) {
      return 'Not checked yet'
    }

    return new Intl.DateTimeFormat(undefined, {
      hour: 'numeric',
      minute: '2-digit',
      second: '2-digit',
    }).format(timestamp)
  }

  $effect(() => {
    backendStatus.start()

    return () => {
      backendStatus.stop()
    }
  })
</script>

<section class="flex h-full min-h-0 flex-col bg-[var(--color-bg)] text-[var(--color-text)]">
  <div class="flex-1 overflow-y-auto px-4 py-6 sm:px-6">
    <div class="mx-auto flex w-full max-w-4xl flex-col gap-6">
      <div class="rounded-3xl border border-[var(--color-border)] bg-[var(--color-panel)] px-5 py-5">
        <p class="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-accent)]">
          Backend
        </p>
        <h2 class="mt-2 text-xl font-semibold text-[var(--color-text)]">Bun Server Status</h2>
        <p class="mt-2 text-sm text-[var(--color-muted)]">
          This panel shows server reachability from the `/health` endpoint and the current session WebSocket connection state.
        </p>
      </div>

      <div class="grid gap-4 lg:grid-cols-2">
        <article class="rounded-3xl border border-[var(--color-border)] bg-[var(--color-panel)] px-5 py-5">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
                HTTP Health
              </p>
              <h3 class="mt-2 text-lg font-semibold text-[var(--color-text)]">Reachability</h3>
            </div>
            <span class={`inline-flex rounded-full border px-3 py-1 text-xs font-semibold uppercase tracking-[0.12em] ${backendHealthTone}`}>
              {backendHealthLabel}
            </span>
          </div>

          <dl class="mt-4 flex flex-col gap-4 text-sm">
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">Health endpoint</dt>
              <dd class="break-all font-mono text-xs text-[var(--color-text)]">{backendStatus.endpoint}</dd>
            </div>
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">Last checked</dt>
              <dd class="text-[var(--color-text)]">{lastCheckedLabel}</dd>
            </div>
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">Latest health error</dt>
              <dd class={backendStatus.error ? 'text-rose-300' : 'text-[var(--color-muted)]'}>
                {backendStatus.error || 'None'}
              </dd>
            </div>
          </dl>
        </article>

        <article class="rounded-3xl border border-[var(--color-border)] bg-[var(--color-panel)] px-5 py-5">
          <div class="flex items-start justify-between gap-3">
            <div>
              <p class="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
                Session Socket
              </p>
              <h3 class="mt-2 text-lg font-semibold text-[var(--color-text)]">Renderer Connection</h3>
            </div>
            <span class={`inline-flex rounded-full border px-3 py-1 text-xs font-semibold uppercase tracking-[0.12em] ${sessionConnectionTone}`}>
              {sessionConnectionLabel}
            </span>
          </div>

          <dl class="mt-4 flex flex-col gap-4 text-sm">
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">Session id</dt>
              <dd class="text-[var(--color-text)]">{session.sessionId}</dd>
            </div>
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">WebSocket endpoint</dt>
              <dd class="break-all font-mono text-xs text-[var(--color-text)]">{sessionEndpoint}</dd>
            </div>
            <div class="flex flex-col gap-1">
              <dt class="font-semibold text-[var(--color-muted)]">Latest session error</dt>
              <dd class={session.error ? 'text-rose-300' : 'text-[var(--color-muted)]'}>
                {session.error || 'None'}
              </dd>
            </div>
          </dl>
        </article>
      </div>
    </div>
  </div>
</section>

// electron-react/src/components/backend/BackendStatusPane.tsx
import { useCallback, useEffect, useRef, useState } from 'react'

import type { BackendHealthStatus, BackendStatusSnapshot } from '../../lib/types/backend'

type BackendServerAction = 'start' | 'stop' | 'restart' | null

const statusPollIntervalMs = 2_000

/** Returns the human-readable label for one backend health state. */
function getBackendHealthLabel(status: BackendHealthStatus): string {
  if (status === 'healthy') {
    return 'Healthy'
  }

  if (status === 'starting') {
    return 'Starting'
  }

  if (status === 'unreachable') {
    return 'Unreachable'
  }

  return 'Stopped'
}

/** Returns the badge classes for one backend health state. */
function getBackendHealthTone(status: BackendHealthStatus): string {
  if (status === 'healthy') {
    return 'border-emerald-500/30 bg-emerald-500/12 text-emerald-300'
  }

  if (status === 'starting') {
    return 'border-sky-500/30 bg-sky-500/12 text-sky-300'
  }

  if (status === 'unreachable') {
    return 'border-rose-500/30 bg-rose-500/12 text-rose-300'
  }

  return 'border-[var(--color-border)] bg-[var(--color-panel)] text-[var(--color-muted)]'
}

/** Returns the status-panel button label for one pending backend action. */
function getPendingActionLabel(action: BackendServerAction): string {
  if (action === 'start') {
    return 'Starting server...'
  }

  if (action === 'stop') {
    return 'Stopping server...'
  }

  if (action === 'restart') {
    return 'Restarting server...'
  }

  return ''
}

/** Returns the display value for one optional backend metadata field. */
function formatOptionalMetadata(value: string | null | undefined): string {
  return value && value.length > 0 ? value : 'Unavailable'
}

/** Renders the backend status panel with local server lifecycle controls. */
export function BackendStatusPane(): JSX.Element {
  const [snapshot, setSnapshot] = useState<BackendStatusSnapshot | null>(null)
  const [isCheckingStatus, setIsCheckingStatus] = useState(true)
  const [statusError, setStatusError] = useState('')
  const [pendingAction, setPendingAction] = useState<BackendServerAction>(null)
  const [actionError, setActionError] = useState('')
  const hasLoadedStatusRef = useRef(false)

  /** Refreshes the backend status snapshot from the Electron bridge. */
  const refreshStatus = useCallback(async (): Promise<void> => {
    if (!hasLoadedStatusRef.current) {
      setIsCheckingStatus(true)
    }

    try {
      const nextSnapshot = await window.videApi.getBackendStatus()
      setSnapshot(nextSnapshot)
      setStatusError('')
    } catch (error) {
      setStatusError(error instanceof Error ? error.message : 'The backend status check failed.')
    } finally {
      hasLoadedStatusRef.current = true
      setIsCheckingStatus(false)
    }
  }, [])

  useEffect(() => {
    let isDisposed = false

    /** Runs one guarded status refresh while the panel is still mounted. */
    async function refreshWhileMounted(): Promise<void> {
      if (isDisposed) {
        return
      }

      await refreshStatus()
    }

    void refreshWhileMounted()
    const intervalId = window.setInterval(() => {
      void refreshWhileMounted()
    }, statusPollIntervalMs)

    return () => {
      isDisposed = true
      window.clearInterval(intervalId)
    }
  }, [refreshStatus])

  /** Runs one backend lifecycle action through the Electron bridge. */
  const runServerAction = useCallback(
    async (action: Exclude<BackendServerAction, null>): Promise<void> => {
      if (pendingAction) {
        return
      }

      setPendingAction(action)
      setActionError('')

      try {
        if (action === 'start') {
          await window.videApi.startBackend()
        } else if (action === 'stop') {
          await window.videApi.stopBackend()
        } else {
          await window.videApi.restartBackend()
        }

        await refreshStatus()
      } catch (error) {
        setActionError(error instanceof Error ? error.message : `The ${action} request failed.`)
        await refreshStatus()
      } finally {
        setPendingAction(null)
      }
    },
    [pendingAction, refreshStatus],
  )

  const currentStatus = snapshot?.healthStatus ?? 'stopped'
  const statusLabel = isCheckingStatus ? 'Checking...' : getBackendHealthLabel(currentStatus)
  const statusTone = isCheckingStatus
    ? 'border-sky-500/30 bg-sky-500/12 text-sky-300'
    : getBackendHealthTone(currentStatus)
  const displayedError = actionError || statusError || snapshot?.error || ''

  return (
    <section className="flex h-full min-h-0 flex-col gap-4 bg-[var(--color-bg)] p-5 text-[var(--color-text)]">
      <div className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-panel)] p-4">
        <div className="flex items-center justify-between gap-3">
          <div>
            <h2 className="text-base font-semibold">Backend Status</h2>
            <p className="mt-1 text-sm text-[var(--color-muted)]">
              Local server controls for development.
            </p>
          </div>
          <span className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusTone}`}>
            {statusLabel}
          </span>
        </div>
      </div>

      <div className="grid gap-3 rounded-2xl border border-[var(--color-border)] bg-[var(--color-panel)] p-4 text-sm">
        <div className="flex items-start justify-between gap-4">
          <p className="pt-0.5 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
            Health endpoint
          </p>
          <p className="max-w-[65%] break-all text-right text-[var(--color-text)]">
            {snapshot?.healthUrl ?? 'Loading...'}
          </p>
        </div>

        <div className="flex items-start justify-between gap-4">
          <p className="pt-0.5 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
            Process
          </p>
          <p className="text-right text-[var(--color-text)]">
            {snapshot?.processId === null || snapshot?.processId === undefined
              ? 'Not running'
              : `PID ${snapshot.processId}`}
          </p>
        </div>

        <div className="flex items-start justify-between gap-4">
          <p className="pt-0.5 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
            Started at
          </p>
          <p className="max-w-[65%] break-all text-right text-[var(--color-text)]">
            {formatOptionalMetadata(snapshot?.startedAt)}
          </p>
        </div>

        <div className="flex items-start justify-between gap-4">
          <p className="pt-0.5 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
            Instance ID
          </p>
          <p className="max-w-[65%] break-all text-right text-[var(--color-text)]">
            {formatOptionalMetadata(snapshot?.instanceId)}
          </p>
        </div>

        <div className="flex items-start justify-between gap-4">
          <p className="pt-0.5 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--color-muted)]">
            Server hash
          </p>
          <p className="max-w-[65%] break-all text-right text-[var(--color-text)]">
            {formatOptionalMetadata(snapshot?.serverTypeHash)}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <button
          type="button"
          className="rounded-xl border border-[var(--color-border)] bg-[var(--color-panel)] px-4 py-2 text-sm font-medium text-[var(--color-text)] transition hover:border-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-50"
          onClick={() => void runServerAction('start')}
          disabled={pendingAction !== null || !snapshot?.supportsStart}
        >
          Start server
        </button>
        <button
          type="button"
          className="rounded-xl border border-[var(--color-border)] bg-[var(--color-panel)] px-4 py-2 text-sm font-medium text-[var(--color-text)] transition hover:border-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-50"
          onClick={() => void runServerAction('stop')}
          disabled={pendingAction !== null || !snapshot?.supportsStop}
        >
          Stop server
        </button>
        <button
          type="button"
          className="rounded-xl border border-[var(--color-border)] bg-[var(--color-panel)] px-4 py-2 text-sm font-medium text-[var(--color-text)] transition hover:border-[var(--color-accent)] disabled:cursor-not-allowed disabled:opacity-50"
          onClick={() => void runServerAction('restart')}
          disabled={pendingAction !== null || !snapshot?.supportsRestart}
        >
          Restart server
        </button>
      </div>

      {pendingAction ? (
        <div className="rounded-2xl border border-sky-500/30 bg-sky-500/12 px-4 py-3 text-sm text-sky-200">
          {getPendingActionLabel(pendingAction)}
        </div>
      ) : null}

      {displayedError ? (
        <div className="rounded-2xl border border-rose-500/30 bg-rose-500/12 px-4 py-3 text-sm text-rose-200">
          {displayedError}
        </div>
      ) : null}
    </section>
  )
}
